name: flutter_khipu
description: "Flutter plugin for Khipu, this plugin enables a flutter app to use Khipu to authorize payments."
version: 1.5.1
homepage: "https://github.com/khipu/flutter_khipu"

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.khipu.flutter_khipu
        pluginClass: FlutterKhipuPlugin
      ios:
        pluginClass: FlutterKhipuPlugin
