name: flutter_khipu
description: "Flutter plugin for Khipu, this plugin enables a flutter app to use Khipu to authorize payments."
version: 1.9.0
homepage: "https://github.com/khipu/flutter_khipu"
repository: "https://github.com/khipu/flutter_khipu"
issue_tracker: "https://github.com/khipu/flutter_khipu/issues"
topics: [payments, khipu, chile, fintech]

environment:
  sdk: ^3.12.0
  flutter: '>=3.44.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.khipu.flutter_khipu
        pluginClass: FlutterKhipuPlugin
      ios:
        pluginClass: FlutterKhipuPlugin
