// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.khipu.flutter_khipu

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Tema con el que Khipu se presenta. */
enum class KhipuTheme(val raw: Int) {
  LIGHT(0),
  DARK(1),
  SYSTEM(2);

  companion object {
    fun ofRaw(raw: Int): KhipuTheme? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Desenlace de la operación.
 *
 * El SDK lo entrega como texto libre. Los cinco primeros casos son los que
 * `khipu-client-android` 2.28.5 puede emitir, medidos sobre su bytecode;
 * [unknown] existe para que un valor nuevo del servidor no rompa el canal.
 * Sin él, un valor no reconocido haría fallar la decodificación entera del
 * mensaje y el pago llegaría al comercio como un error de plataforma.
 */
enum class KhipuResultStatus(val raw: Int) {
  OK(0),
  ERROR(1),
  WARNING(2),
  /**
   * El SDK lo emite como `CONTINUE`. Se llama distinto porque `continue` es
   * palabra reservada en Dart, en Kotlin y en Swift.
   */
  MUST_CONTINUE(3),
  USER_CANCELED(4),
  UNKNOWN(5);

  companion object {
    fun ofRaw(raw: Int): KhipuResultStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Paleta con la que se pinta Khipu. Un color nulo deja el del SDK.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class KhipuColors (
  val lightBackground: String? = null,
  val lightOnBackground: String? = null,
  val lightPrimary: String? = null,
  val lightOnPrimary: String? = null,
  val lightTopBarContainer: String? = null,
  val lightOnTopBarContainer: String? = null,
  val darkBackground: String? = null,
  val darkOnBackground: String? = null,
  val darkPrimary: String? = null,
  val darkOnPrimary: String? = null,
  val darkTopBarContainer: String? = null,
  val darkOnTopBarContainer: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KhipuColors {
      val lightBackground = pigeonVar_list[0] as String?
      val lightOnBackground = pigeonVar_list[1] as String?
      val lightPrimary = pigeonVar_list[2] as String?
      val lightOnPrimary = pigeonVar_list[3] as String?
      val lightTopBarContainer = pigeonVar_list[4] as String?
      val lightOnTopBarContainer = pigeonVar_list[5] as String?
      val darkBackground = pigeonVar_list[6] as String?
      val darkOnBackground = pigeonVar_list[7] as String?
      val darkPrimary = pigeonVar_list[8] as String?
      val darkOnPrimary = pigeonVar_list[9] as String?
      val darkTopBarContainer = pigeonVar_list[10] as String?
      val darkOnTopBarContainer = pigeonVar_list[11] as String?
      return KhipuColors(lightBackground, lightOnBackground, lightPrimary, lightOnPrimary, lightTopBarContainer, lightOnTopBarContainer, darkBackground, darkOnBackground, darkPrimary, darkOnPrimary, darkTopBarContainer, darkOnTopBarContainer)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      lightBackground,
      lightOnBackground,
      lightPrimary,
      lightOnPrimary,
      lightTopBarContainer,
      lightOnTopBarContainer,
      darkBackground,
      darkOnBackground,
      darkPrimary,
      darkOnPrimary,
      darkTopBarContainer,
      darkOnTopBarContainer,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KhipuColors
    return MessagesPigeonUtils.deepEquals(this.lightBackground, other.lightBackground) && MessagesPigeonUtils.deepEquals(this.lightOnBackground, other.lightOnBackground) && MessagesPigeonUtils.deepEquals(this.lightPrimary, other.lightPrimary) && MessagesPigeonUtils.deepEquals(this.lightOnPrimary, other.lightOnPrimary) && MessagesPigeonUtils.deepEquals(this.lightTopBarContainer, other.lightTopBarContainer) && MessagesPigeonUtils.deepEquals(this.lightOnTopBarContainer, other.lightOnTopBarContainer) && MessagesPigeonUtils.deepEquals(this.darkBackground, other.darkBackground) && MessagesPigeonUtils.deepEquals(this.darkOnBackground, other.darkOnBackground) && MessagesPigeonUtils.deepEquals(this.darkPrimary, other.darkPrimary) && MessagesPigeonUtils.deepEquals(this.darkOnPrimary, other.darkOnPrimary) && MessagesPigeonUtils.deepEquals(this.darkTopBarContainer, other.darkTopBarContainer) && MessagesPigeonUtils.deepEquals(this.darkOnTopBarContainer, other.darkOnTopBarContainer)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.lightBackground)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.lightOnBackground)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.lightPrimary)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.lightOnPrimary)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.lightTopBarContainer)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.lightOnTopBarContainer)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.darkBackground)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.darkOnBackground)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.darkPrimary)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.darkOnPrimary)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.darkTopBarContainer)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.darkOnTopBarContainer)
    return result
  }
  override fun toString(): String {
    return "KhipuColors(lightBackground=$lightBackground, lightOnBackground=$lightOnBackground, lightPrimary=$lightPrimary, lightOnPrimary=$lightOnPrimary, lightTopBarContainer=$lightTopBarContainer, lightOnTopBarContainer=$lightOnTopBarContainer, darkBackground=$darkBackground, darkOnBackground=$darkOnBackground, darkPrimary=$darkPrimary, darkOnPrimary=$darkOnPrimary, darkTopBarContainer=$darkTopBarContainer, darkOnTopBarContainer=$darkOnTopBarContainer)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KhipuStartOperationOptions (
  val operationId: String,
  val locale: String? = null,
  val title: String? = null,
  val titleImageUrl: String? = null,
  val skipExitPage: Boolean? = null,
  val skipExitSuccessPage: Boolean? = null,
  val showFooter: Boolean? = null,
  val showMerchantLogo: Boolean? = null,
  val showPaymentDetails: Boolean? = null,
  val theme: KhipuTheme? = null,
  val colors: KhipuColors? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KhipuStartOperationOptions {
      val operationId = pigeonVar_list[0] as String
      val locale = pigeonVar_list[1] as String?
      val title = pigeonVar_list[2] as String?
      val titleImageUrl = pigeonVar_list[3] as String?
      val skipExitPage = pigeonVar_list[4] as Boolean?
      val skipExitSuccessPage = pigeonVar_list[5] as Boolean?
      val showFooter = pigeonVar_list[6] as Boolean?
      val showMerchantLogo = pigeonVar_list[7] as Boolean?
      val showPaymentDetails = pigeonVar_list[8] as Boolean?
      val theme = pigeonVar_list[9] as KhipuTheme?
      val colors = pigeonVar_list[10] as KhipuColors?
      return KhipuStartOperationOptions(operationId, locale, title, titleImageUrl, skipExitPage, skipExitSuccessPage, showFooter, showMerchantLogo, showPaymentDetails, theme, colors)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      operationId,
      locale,
      title,
      titleImageUrl,
      skipExitPage,
      skipExitSuccessPage,
      showFooter,
      showMerchantLogo,
      showPaymentDetails,
      theme,
      colors,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KhipuStartOperationOptions
    return MessagesPigeonUtils.deepEquals(this.operationId, other.operationId) && MessagesPigeonUtils.deepEquals(this.locale, other.locale) && MessagesPigeonUtils.deepEquals(this.title, other.title) && MessagesPigeonUtils.deepEquals(this.titleImageUrl, other.titleImageUrl) && MessagesPigeonUtils.deepEquals(this.skipExitPage, other.skipExitPage) && MessagesPigeonUtils.deepEquals(this.skipExitSuccessPage, other.skipExitSuccessPage) && MessagesPigeonUtils.deepEquals(this.showFooter, other.showFooter) && MessagesPigeonUtils.deepEquals(this.showMerchantLogo, other.showMerchantLogo) && MessagesPigeonUtils.deepEquals(this.showPaymentDetails, other.showPaymentDetails) && MessagesPigeonUtils.deepEquals(this.theme, other.theme) && MessagesPigeonUtils.deepEquals(this.colors, other.colors)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.operationId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.locale)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.title)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.titleImageUrl)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.skipExitPage)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.skipExitSuccessPage)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.showFooter)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.showMerchantLogo)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.showPaymentDetails)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.theme)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.colors)
    return result
  }
  override fun toString(): String {
    return "KhipuStartOperationOptions(operationId=$operationId, locale=$locale, title=$title, titleImageUrl=$titleImageUrl, skipExitPage=$skipExitPage, skipExitSuccessPage=$skipExitSuccessPage, showFooter=$showFooter, showMerchantLogo=$showMerchantLogo, showPaymentDetails=$showPaymentDetails, theme=$theme, colors=$colors)"
  }
}

/**
 * Los tres campos son no nulos: medido sobre el AAR 2.28.5, el constructor
 * de `com.khipu.client.KhipuEvent` hace `checkNotNullParameter` en los tres.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class KhipuEvent (
  val name: String,
  val type: String,
  val timestamp: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KhipuEvent {
      val name = pigeonVar_list[0] as String
      val type = pigeonVar_list[1] as String
      val timestamp = pigeonVar_list[2] as String
      return KhipuEvent(name, type, timestamp)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      type,
      timestamp,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KhipuEvent
    return MessagesPigeonUtils.deepEquals(this.name, other.name) && MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.timestamp, other.timestamp)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.name)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.timestamp)
    return result
  }
  override fun toString(): String {
    return "KhipuEvent(name=$name, type=$type, timestamp=$timestamp)"
  }
}

/**
 * Nulabilidad según §2.3 del design doc: los tres opcionales son exactamente
 * los que el SDK Android declara `@Nullable`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class KhipuResult (
  val operationId: String,
  val result: KhipuResultStatus,
  val exitTitle: String,
  val exitMessage: String,
  val events: List<KhipuEvent>,
  val exitUrl: String? = null,
  val failureReason: String? = null,
  val continueUrl: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KhipuResult {
      val operationId = pigeonVar_list[0] as String
      val result = pigeonVar_list[1] as KhipuResultStatus
      val exitTitle = pigeonVar_list[2] as String
      val exitMessage = pigeonVar_list[3] as String
      val events = pigeonVar_list[4] as List<KhipuEvent>
      val exitUrl = pigeonVar_list[5] as String?
      val failureReason = pigeonVar_list[6] as String?
      val continueUrl = pigeonVar_list[7] as String?
      return KhipuResult(operationId, result, exitTitle, exitMessage, events, exitUrl, failureReason, continueUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      operationId,
      result,
      exitTitle,
      exitMessage,
      events,
      exitUrl,
      failureReason,
      continueUrl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KhipuResult
    return MessagesPigeonUtils.deepEquals(this.operationId, other.operationId) && MessagesPigeonUtils.deepEquals(this.result, other.result) && MessagesPigeonUtils.deepEquals(this.exitTitle, other.exitTitle) && MessagesPigeonUtils.deepEquals(this.exitMessage, other.exitMessage) && MessagesPigeonUtils.deepEquals(this.events, other.events) && MessagesPigeonUtils.deepEquals(this.exitUrl, other.exitUrl) && MessagesPigeonUtils.deepEquals(this.failureReason, other.failureReason) && MessagesPigeonUtils.deepEquals(this.continueUrl, other.continueUrl)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.operationId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.result)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.exitTitle)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.exitMessage)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.events)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.exitUrl)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.failureReason)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.continueUrl)
    return result
  }
  override fun toString(): String {
    return "KhipuResult(operationId=$operationId, result=$result, exitTitle=$exitTitle, exitMessage=$exitMessage, events=$events, exitUrl=$exitUrl, failureReason=$failureReason, continueUrl=$continueUrl)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KhipuTheme.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KhipuResultStatus.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KhipuColors.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KhipuStartOperationOptions.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KhipuEvent.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KhipuResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is KhipuTheme -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is KhipuResultStatus -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is KhipuColors -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is KhipuStartOperationOptions -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is KhipuEvent -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is KhipuResult -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface KhipuHostApi {
  suspend fun startOperation(options: KhipuStartOperationOptions): KhipuResult?

  companion object {
    /** The codec used by KhipuHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `KhipuHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: KhipuHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_khipu.KhipuHostApi.startOperation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as KhipuStartOperationOptions
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.startOperation(optionsArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
