// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Theme Khipu presents itself with.
enum KhipuTheme {
  light,
  dark,
  system;
}

/// Outcome of the operation.
///
/// The SDK delivers it as free text. The first five cases are the ones
/// `khipu-client-android` 2.28.5 can emit, measured against its bytecode;
/// [unknown] exists so a new value from the server doesn't break the
/// channel. Without it, an unrecognized value would fail decoding of the
/// entire message, and the payment would reach the merchant as a platform
/// error.
enum KhipuResultStatus {
  ok,
  error,
  warning,
  /// The SDK emits this as `CONTINUE`. It's named differently because
  /// `continue` is a reserved word in Dart, Kotlin, and Swift.
  mustContinue,
  /// Reserved: the abandonment path does NOT report this.
  ///
  /// The native SDK defines the constant, so it is kept here, but a payer who
  /// walks away arrives as [error] with `failureReason` set to
  /// `"USER_CANCELED"` — measured on `khipu-client-android 2.28.5`. Branching
  /// on this case alone silently never matches; branch on `failureReason`.
  userCanceled,
  unknown;
}

/// Palette Khipu is painted with. A null color leaves the SDK's own.
class KhipuColors {
  KhipuColors({
    this.lightBackground,
    this.lightOnBackground,
    this.lightPrimary,
    this.lightOnPrimary,
    this.lightTopBarContainer,
    this.lightOnTopBarContainer,
    this.darkBackground,
    this.darkOnBackground,
    this.darkPrimary,
    this.darkOnPrimary,
    this.darkTopBarContainer,
    this.darkOnTopBarContainer,
  });

  String? lightBackground;

  String? lightOnBackground;

  String? lightPrimary;

  String? lightOnPrimary;

  String? lightTopBarContainer;

  String? lightOnTopBarContainer;

  String? darkBackground;

  String? darkOnBackground;

  String? darkPrimary;

  String? darkOnPrimary;

  String? darkTopBarContainer;

  String? darkOnTopBarContainer;

  List<Object?> _toList() {
    return <Object?>[
      lightBackground,
      lightOnBackground,
      lightPrimary,
      lightOnPrimary,
      lightTopBarContainer,
      lightOnTopBarContainer,
      darkBackground,
      darkOnBackground,
      darkPrimary,
      darkOnPrimary,
      darkTopBarContainer,
      darkOnTopBarContainer,
    ];
  }

  Object encode() {
    return _toList();  }

  static KhipuColors decode(Object result) {
    result as List<Object?>;
    return KhipuColors(
      lightBackground: result[0] as String?,
      lightOnBackground: result[1] as String?,
      lightPrimary: result[2] as String?,
      lightOnPrimary: result[3] as String?,
      lightTopBarContainer: result[4] as String?,
      lightOnTopBarContainer: result[5] as String?,
      darkBackground: result[6] as String?,
      darkOnBackground: result[7] as String?,
      darkPrimary: result[8] as String?,
      darkOnPrimary: result[9] as String?,
      darkTopBarContainer: result[10] as String?,
      darkOnTopBarContainer: result[11] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KhipuColors || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(lightBackground, other.lightBackground) && _deepEquals(lightOnBackground, other.lightOnBackground) && _deepEquals(lightPrimary, other.lightPrimary) && _deepEquals(lightOnPrimary, other.lightOnPrimary) && _deepEquals(lightTopBarContainer, other.lightTopBarContainer) && _deepEquals(lightOnTopBarContainer, other.lightOnTopBarContainer) && _deepEquals(darkBackground, other.darkBackground) && _deepEquals(darkOnBackground, other.darkOnBackground) && _deepEquals(darkPrimary, other.darkPrimary) && _deepEquals(darkOnPrimary, other.darkOnPrimary) && _deepEquals(darkTopBarContainer, other.darkTopBarContainer) && _deepEquals(darkOnTopBarContainer, other.darkOnTopBarContainer);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KhipuColors(lightBackground: $lightBackground, lightOnBackground: $lightOnBackground, lightPrimary: $lightPrimary, lightOnPrimary: $lightOnPrimary, lightTopBarContainer: $lightTopBarContainer, lightOnTopBarContainer: $lightOnTopBarContainer, darkBackground: $darkBackground, darkOnBackground: $darkOnBackground, darkPrimary: $darkPrimary, darkOnPrimary: $darkOnPrimary, darkTopBarContainer: $darkTopBarContainer, darkOnTopBarContainer: $darkOnTopBarContainer)';
  }
}

class KhipuStartOperationOptions {
  KhipuStartOperationOptions({
    required this.operationId,
    this.locale,
    this.title,
    this.titleImageUrl,
    this.skipExitPage,
    this.skipExitSuccessPage,
    this.showFooter,
    this.showMerchantLogo,
    this.showPaymentDetails,
    this.theme,
    this.colors,
  });

  String operationId;

  String? locale;

  String? title;

  String? titleImageUrl;

  bool? skipExitPage;

  bool? skipExitSuccessPage;

  bool? showFooter;

  bool? showMerchantLogo;

  bool? showPaymentDetails;

  KhipuTheme? theme;

  KhipuColors? colors;

  List<Object?> _toList() {
    return <Object?>[
      operationId,
      locale,
      title,
      titleImageUrl,
      skipExitPage,
      skipExitSuccessPage,
      showFooter,
      showMerchantLogo,
      showPaymentDetails,
      theme,
      colors,
    ];
  }

  Object encode() {
    return _toList();  }

  static KhipuStartOperationOptions decode(Object result) {
    result as List<Object?>;
    return KhipuStartOperationOptions(
      operationId: result[0]! as String,
      locale: result[1] as String?,
      title: result[2] as String?,
      titleImageUrl: result[3] as String?,
      skipExitPage: result[4] as bool?,
      skipExitSuccessPage: result[5] as bool?,
      showFooter: result[6] as bool?,
      showMerchantLogo: result[7] as bool?,
      showPaymentDetails: result[8] as bool?,
      theme: result[9] as KhipuTheme?,
      colors: result[10] as KhipuColors?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KhipuStartOperationOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(operationId, other.operationId) && _deepEquals(locale, other.locale) && _deepEquals(title, other.title) && _deepEquals(titleImageUrl, other.titleImageUrl) && _deepEquals(skipExitPage, other.skipExitPage) && _deepEquals(skipExitSuccessPage, other.skipExitSuccessPage) && _deepEquals(showFooter, other.showFooter) && _deepEquals(showMerchantLogo, other.showMerchantLogo) && _deepEquals(showPaymentDetails, other.showPaymentDetails) && _deepEquals(theme, other.theme) && _deepEquals(colors, other.colors);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KhipuStartOperationOptions(operationId: $operationId, locale: $locale, title: $title, titleImageUrl: $titleImageUrl, skipExitPage: $skipExitPage, skipExitSuccessPage: $skipExitSuccessPage, showFooter: $showFooter, showMerchantLogo: $showMerchantLogo, showPaymentDetails: $showPaymentDetails, theme: $theme, colors: $colors)';
  }
}

/// All three fields are non-null: measured against the 2.28.5 AAR, the
/// `com.khipu.client.KhipuEvent` constructor does `checkNotNullParameter` on
/// all three.
class KhipuEvent {
  KhipuEvent({
    required this.name,
    required this.type,
    required this.timestamp,
  });

  String name;

  String type;

  String timestamp;

  List<Object?> _toList() {
    return <Object?>[
      name,
      type,
      timestamp,
    ];
  }

  Object encode() {
    return _toList();  }

  static KhipuEvent decode(Object result) {
    result as List<Object?>;
    return KhipuEvent(
      name: result[0]! as String,
      type: result[1]! as String,
      timestamp: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KhipuEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) && _deepEquals(type, other.type) && _deepEquals(timestamp, other.timestamp);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KhipuEvent(name: $name, type: $type, timestamp: $timestamp)';
  }
}

/// Nullability per §2.3 of the design doc: the three optional fields are
/// exactly the ones the Android SDK declares `@Nullable`.
class KhipuResult {
  KhipuResult({
    required this.operationId,
    required this.result,
    required this.rawResult,
    required this.exitTitle,
    required this.exitMessage,
    required this.events,
    this.exitUrl,
    this.failureReason,
    this.continueUrl,
  });

  String operationId;

  KhipuResultStatus result;

  /// What the SDK actually sent for [result], before it was matched against
  /// the known cases. Always present, even when [result] is not
  /// [KhipuResultStatus.unknown]: this is what lets a merchant log, report
  /// to support, or otherwise handle a value this plugin doesn't recognize
  /// yet, without waiting for a plugin release that adds it.
  String rawResult;

  String exitTitle;

  String exitMessage;

  List<KhipuEvent> events;

  String? exitUrl;

  String? failureReason;

  String? continueUrl;

  List<Object?> _toList() {
    return <Object?>[
      operationId,
      result,
      rawResult,
      exitTitle,
      exitMessage,
      events,
      exitUrl,
      failureReason,
      continueUrl,
    ];
  }

  Object encode() {
    return _toList();  }

  static KhipuResult decode(Object result) {
    result as List<Object?>;
    return KhipuResult(
      operationId: result[0]! as String,
      result: result[1]! as KhipuResultStatus,
      rawResult: result[2]! as String,
      exitTitle: result[3]! as String,
      exitMessage: result[4]! as String,
      events: (result[5]! as List<Object?>).cast<KhipuEvent>(),
      exitUrl: result[6] as String?,
      failureReason: result[7] as String?,
      continueUrl: result[8] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KhipuResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(operationId, other.operationId) && _deepEquals(result, other.result) && _deepEquals(rawResult, other.rawResult) && _deepEquals(exitTitle, other.exitTitle) && _deepEquals(exitMessage, other.exitMessage) && _deepEquals(events, other.events) && _deepEquals(exitUrl, other.exitUrl) && _deepEquals(failureReason, other.failureReason) && _deepEquals(continueUrl, other.continueUrl);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KhipuResult(operationId: $operationId, result: $result, rawResult: $rawResult, exitTitle: $exitTitle, exitMessage: $exitMessage, events: $events, exitUrl: $exitUrl, failureReason: $failureReason, continueUrl: $continueUrl)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is KhipuTheme) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is KhipuResultStatus) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is KhipuColors) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is KhipuStartOperationOptions) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is KhipuEvent) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is KhipuResult) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : KhipuTheme.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : KhipuResultStatus.values[value];
      case 131:
        return KhipuColors.decode(readValue(buffer)!);
      case 132:
        return KhipuStartOperationOptions.decode(readValue(buffer)!);
      case 133:
        return KhipuEvent.decode(readValue(buffer)!);
      case 134:
        return KhipuResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class KhipuHostApi {
  /// Constructor for [KhipuHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  KhipuHostApi({
      BinaryMessenger? binaryMessenger, 
      String messageChannelSuffix = '', 
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  Future<KhipuResult?> startOperation(KhipuStartOperationOptions options) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_khipu.KhipuHostApi.startOperation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as KhipuResult?;
  }
}
