// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Theme Khipu presents itself with.
enum KhipuTheme: Int, CaseIterable {
  case light = 0
  case dark = 1
  case system = 2
}

/// Outcome of the operation.
///
/// The SDK delivers it as free text. The first five cases are the ones
/// `khipu-client-android` 2.28.5 can emit, measured against its bytecode;
/// [unknown] exists so a new value from the server doesn't break the
/// channel. Without it, an unrecognized value would fail decoding of the
/// entire message, and the payment would reach the merchant as a platform
/// error.
enum KhipuResultStatus: Int, CaseIterable {
  case ok = 0
  case error = 1
  case warning = 2
  /// The SDK emits this as `CONTINUE`. It's named differently because
  /// `continue` is a reserved word in Dart, Kotlin, and Swift.
  case mustContinue = 3
  case userCanceled = 4
  case unknown = 5
}

/// Palette Khipu is painted with. A null color leaves the SDK's own.
///
/// Generated class from Pigeon that represents data sent in messages.
struct KhipuColors: Hashable, CustomStringConvertible {
  var lightBackground: String? = nil
  var lightOnBackground: String? = nil
  var lightPrimary: String? = nil
  var lightOnPrimary: String? = nil
  var lightTopBarContainer: String? = nil
  var lightOnTopBarContainer: String? = nil
  var darkBackground: String? = nil
  var darkOnBackground: String? = nil
  var darkPrimary: String? = nil
  var darkOnPrimary: String? = nil
  var darkTopBarContainer: String? = nil
  var darkOnTopBarContainer: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KhipuColors? {
    let lightBackground: String? = nilOrValue(pigeonVar_list[0])
    let lightOnBackground: String? = nilOrValue(pigeonVar_list[1])
    let lightPrimary: String? = nilOrValue(pigeonVar_list[2])
    let lightOnPrimary: String? = nilOrValue(pigeonVar_list[3])
    let lightTopBarContainer: String? = nilOrValue(pigeonVar_list[4])
    let lightOnTopBarContainer: String? = nilOrValue(pigeonVar_list[5])
    let darkBackground: String? = nilOrValue(pigeonVar_list[6])
    let darkOnBackground: String? = nilOrValue(pigeonVar_list[7])
    let darkPrimary: String? = nilOrValue(pigeonVar_list[8])
    let darkOnPrimary: String? = nilOrValue(pigeonVar_list[9])
    let darkTopBarContainer: String? = nilOrValue(pigeonVar_list[10])
    let darkOnTopBarContainer: String? = nilOrValue(pigeonVar_list[11])

    return KhipuColors(
      lightBackground: lightBackground,
      lightOnBackground: lightOnBackground,
      lightPrimary: lightPrimary,
      lightOnPrimary: lightOnPrimary,
      lightTopBarContainer: lightTopBarContainer,
      lightOnTopBarContainer: lightOnTopBarContainer,
      darkBackground: darkBackground,
      darkOnBackground: darkOnBackground,
      darkPrimary: darkPrimary,
      darkOnPrimary: darkOnPrimary,
      darkTopBarContainer: darkTopBarContainer,
      darkOnTopBarContainer: darkOnTopBarContainer
    )
  }
  func toList() -> [Any?] {
    return [
      lightBackground,
      lightOnBackground,
      lightPrimary,
      lightOnPrimary,
      lightTopBarContainer,
      lightOnTopBarContainer,
      darkBackground,
      darkOnBackground,
      darkPrimary,
      darkOnPrimary,
      darkTopBarContainer,
      darkOnTopBarContainer,
    ]
  }
  static func == (lhs: KhipuColors, rhs: KhipuColors) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.lightBackground, rhs.lightBackground) && MessagesPigeonInternal.deepEquals(lhs.lightOnBackground, rhs.lightOnBackground) && MessagesPigeonInternal.deepEquals(lhs.lightPrimary, rhs.lightPrimary) && MessagesPigeonInternal.deepEquals(lhs.lightOnPrimary, rhs.lightOnPrimary) && MessagesPigeonInternal.deepEquals(lhs.lightTopBarContainer, rhs.lightTopBarContainer) && MessagesPigeonInternal.deepEquals(lhs.lightOnTopBarContainer, rhs.lightOnTopBarContainer) && MessagesPigeonInternal.deepEquals(lhs.darkBackground, rhs.darkBackground) && MessagesPigeonInternal.deepEquals(lhs.darkOnBackground, rhs.darkOnBackground) && MessagesPigeonInternal.deepEquals(lhs.darkPrimary, rhs.darkPrimary) && MessagesPigeonInternal.deepEquals(lhs.darkOnPrimary, rhs.darkOnPrimary) && MessagesPigeonInternal.deepEquals(lhs.darkTopBarContainer, rhs.darkTopBarContainer) && MessagesPigeonInternal.deepEquals(lhs.darkOnTopBarContainer, rhs.darkOnTopBarContainer)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KhipuColors")
    MessagesPigeonInternal.deepHash(value: lightBackground, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: lightOnBackground, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: lightPrimary, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: lightOnPrimary, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: lightTopBarContainer, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: lightOnTopBarContainer, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: darkBackground, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: darkOnBackground, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: darkPrimary, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: darkOnPrimary, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: darkTopBarContainer, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: darkOnTopBarContainer, hasher: &hasher)
  }

  public var description: String {
    return "KhipuColors(lightBackground: \(String(describing: lightBackground)), lightOnBackground: \(String(describing: lightOnBackground)), lightPrimary: \(String(describing: lightPrimary)), lightOnPrimary: \(String(describing: lightOnPrimary)), lightTopBarContainer: \(String(describing: lightTopBarContainer)), lightOnTopBarContainer: \(String(describing: lightOnTopBarContainer)), darkBackground: \(String(describing: darkBackground)), darkOnBackground: \(String(describing: darkOnBackground)), darkPrimary: \(String(describing: darkPrimary)), darkOnPrimary: \(String(describing: darkOnPrimary)), darkTopBarContainer: \(String(describing: darkTopBarContainer)), darkOnTopBarContainer: \(String(describing: darkOnTopBarContainer)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KhipuStartOperationOptions: Hashable, CustomStringConvertible {
  var operationId: String
  var locale: String? = nil
  var title: String? = nil
  var titleImageUrl: String? = nil
  var skipExitPage: Bool? = nil
  var skipExitSuccessPage: Bool? = nil
  var showFooter: Bool? = nil
  var showMerchantLogo: Bool? = nil
  var showPaymentDetails: Bool? = nil
  var theme: KhipuTheme? = nil
  var colors: KhipuColors? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KhipuStartOperationOptions? {
    let operationId = pigeonVar_list[0] as! String
    let locale: String? = nilOrValue(pigeonVar_list[1])
    let title: String? = nilOrValue(pigeonVar_list[2])
    let titleImageUrl: String? = nilOrValue(pigeonVar_list[3])
    let skipExitPage: Bool? = nilOrValue(pigeonVar_list[4])
    let skipExitSuccessPage: Bool? = nilOrValue(pigeonVar_list[5])
    let showFooter: Bool? = nilOrValue(pigeonVar_list[6])
    let showMerchantLogo: Bool? = nilOrValue(pigeonVar_list[7])
    let showPaymentDetails: Bool? = nilOrValue(pigeonVar_list[8])
    let theme: KhipuTheme? = nilOrValue(pigeonVar_list[9])
    let colors: KhipuColors? = nilOrValue(pigeonVar_list[10])

    return KhipuStartOperationOptions(
      operationId: operationId,
      locale: locale,
      title: title,
      titleImageUrl: titleImageUrl,
      skipExitPage: skipExitPage,
      skipExitSuccessPage: skipExitSuccessPage,
      showFooter: showFooter,
      showMerchantLogo: showMerchantLogo,
      showPaymentDetails: showPaymentDetails,
      theme: theme,
      colors: colors
    )
  }
  func toList() -> [Any?] {
    return [
      operationId,
      locale,
      title,
      titleImageUrl,
      skipExitPage,
      skipExitSuccessPage,
      showFooter,
      showMerchantLogo,
      showPaymentDetails,
      theme,
      colors,
    ]
  }
  static func == (lhs: KhipuStartOperationOptions, rhs: KhipuStartOperationOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.operationId, rhs.operationId) && MessagesPigeonInternal.deepEquals(lhs.locale, rhs.locale) && MessagesPigeonInternal.deepEquals(lhs.title, rhs.title) && MessagesPigeonInternal.deepEquals(lhs.titleImageUrl, rhs.titleImageUrl) && MessagesPigeonInternal.deepEquals(lhs.skipExitPage, rhs.skipExitPage) && MessagesPigeonInternal.deepEquals(lhs.skipExitSuccessPage, rhs.skipExitSuccessPage) && MessagesPigeonInternal.deepEquals(lhs.showFooter, rhs.showFooter) && MessagesPigeonInternal.deepEquals(lhs.showMerchantLogo, rhs.showMerchantLogo) && MessagesPigeonInternal.deepEquals(lhs.showPaymentDetails, rhs.showPaymentDetails) && MessagesPigeonInternal.deepEquals(lhs.theme, rhs.theme) && MessagesPigeonInternal.deepEquals(lhs.colors, rhs.colors)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KhipuStartOperationOptions")
    MessagesPigeonInternal.deepHash(value: operationId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: locale, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: title, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: titleImageUrl, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: skipExitPage, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: skipExitSuccessPage, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: showFooter, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: showMerchantLogo, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: showPaymentDetails, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: theme, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: colors, hasher: &hasher)
  }

  public var description: String {
    return "KhipuStartOperationOptions(operationId: \(String(describing: operationId)), locale: \(String(describing: locale)), title: \(String(describing: title)), titleImageUrl: \(String(describing: titleImageUrl)), skipExitPage: \(String(describing: skipExitPage)), skipExitSuccessPage: \(String(describing: skipExitSuccessPage)), showFooter: \(String(describing: showFooter)), showMerchantLogo: \(String(describing: showMerchantLogo)), showPaymentDetails: \(String(describing: showPaymentDetails)), theme: \(String(describing: theme)), colors: \(String(describing: colors)))"
  }
}

/// All three fields are non-null: measured against the 2.28.5 AAR, the
/// `com.khipu.client.KhipuEvent` constructor does `checkNotNullParameter` on
/// all three.
///
/// Generated class from Pigeon that represents data sent in messages.
struct KhipuEvent: Hashable, CustomStringConvertible {
  var name: String
  var type: String
  var timestamp: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KhipuEvent? {
    let name = pigeonVar_list[0] as! String
    let type = pigeonVar_list[1] as! String
    let timestamp = pigeonVar_list[2] as! String

    return KhipuEvent(
      name: name,
      type: type,
      timestamp: timestamp
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      type,
      timestamp,
    ]
  }
  static func == (lhs: KhipuEvent, rhs: KhipuEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.timestamp, rhs.timestamp)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KhipuEvent")
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: timestamp, hasher: &hasher)
  }

  public var description: String {
    return "KhipuEvent(name: \(String(describing: name)), type: \(String(describing: type)), timestamp: \(String(describing: timestamp)))"
  }
}

/// Nullability per §2.3 of the design doc: the three optional fields are
/// exactly the ones the Android SDK declares `@Nullable`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct KhipuResult: Hashable, CustomStringConvertible {
  var operationId: String
  var result: KhipuResultStatus
  /// What the SDK actually sent for [result], before it was matched against
  /// the known cases. Always present, even when [result] is not
  /// [KhipuResultStatus.unknown]: this is what lets a merchant log, report
  /// to support, or otherwise handle a value this plugin doesn't recognize
  /// yet, without waiting for a plugin release that adds it.
  var rawResult: String
  var exitTitle: String
  var exitMessage: String
  var events: [KhipuEvent]
  var exitUrl: String? = nil
  var failureReason: String? = nil
  var continueUrl: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KhipuResult? {
    let operationId = pigeonVar_list[0] as! String
    let result = pigeonVar_list[1] as! KhipuResultStatus
    let rawResult = pigeonVar_list[2] as! String
    let exitTitle = pigeonVar_list[3] as! String
    let exitMessage = pigeonVar_list[4] as! String
    let events = pigeonVar_list[5] as! [KhipuEvent]
    let exitUrl: String? = nilOrValue(pigeonVar_list[6])
    let failureReason: String? = nilOrValue(pigeonVar_list[7])
    let continueUrl: String? = nilOrValue(pigeonVar_list[8])

    return KhipuResult(
      operationId: operationId,
      result: result,
      rawResult: rawResult,
      exitTitle: exitTitle,
      exitMessage: exitMessage,
      events: events,
      exitUrl: exitUrl,
      failureReason: failureReason,
      continueUrl: continueUrl
    )
  }
  func toList() -> [Any?] {
    return [
      operationId,
      result,
      rawResult,
      exitTitle,
      exitMessage,
      events,
      exitUrl,
      failureReason,
      continueUrl,
    ]
  }
  static func == (lhs: KhipuResult, rhs: KhipuResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.operationId, rhs.operationId) && MessagesPigeonInternal.deepEquals(lhs.result, rhs.result) && MessagesPigeonInternal.deepEquals(lhs.rawResult, rhs.rawResult) && MessagesPigeonInternal.deepEquals(lhs.exitTitle, rhs.exitTitle) && MessagesPigeonInternal.deepEquals(lhs.exitMessage, rhs.exitMessage) && MessagesPigeonInternal.deepEquals(lhs.events, rhs.events) && MessagesPigeonInternal.deepEquals(lhs.exitUrl, rhs.exitUrl) && MessagesPigeonInternal.deepEquals(lhs.failureReason, rhs.failureReason) && MessagesPigeonInternal.deepEquals(lhs.continueUrl, rhs.continueUrl)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KhipuResult")
    MessagesPigeonInternal.deepHash(value: operationId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: result, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rawResult, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: exitTitle, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: exitMessage, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: events, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: exitUrl, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: failureReason, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: continueUrl, hasher: &hasher)
  }

  public var description: String {
    return "KhipuResult(operationId: \(String(describing: operationId)), result: \(String(describing: result)), rawResult: \(String(describing: rawResult)), exitTitle: \(String(describing: exitTitle)), exitMessage: \(String(describing: exitMessage)), events: \(String(describing: events)), exitUrl: \(String(describing: exitUrl)), failureReason: \(String(describing: failureReason)), continueUrl: \(String(describing: continueUrl)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KhipuTheme(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KhipuResultStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return KhipuColors.fromList(self.readValue() as! [Any?])
    case 132:
      return KhipuStartOperationOptions.fromList(self.readValue() as! [Any?])
    case 133:
      return KhipuEvent.fromList(self.readValue() as! [Any?])
    case 134:
      return KhipuResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? KhipuTheme {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? KhipuResultStatus {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? KhipuColors {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? KhipuStartOperationOptions {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? KhipuEvent {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? KhipuResult {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol KhipuHostApi {
  func startOperation(options: KhipuStartOperationOptions) async throws -> KhipuResult?
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class KhipuHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `KhipuHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: KhipuHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startOperationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_khipu.KhipuHostApi.startOperation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startOperationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! KhipuStartOperationOptions
        Task { @MainActor in
          do {
            let result = try await api.startOperation(options: optionsArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      startOperationChannel.setMessageHandler(nil)
    }
  }
}
